apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: iggy-nginx-test
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iggy-nginx-test
  template:
    metadata:
      labels:
        app: iggy-nginx-test
    spec:
      containers:
      - name: iggy-nginx-test
        image: igortestacs.azurecr.io/iggy-test-img:0.1
        ports:
        - containerPort: 80
